apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bracket-frontend
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  destination:
    namespace: bracket
    server: https://kubernetes.default.svc
  project: bracket
  source:
    chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.2.0
    helm:
      values: |-

        defaultPodOptions:
          securityContext:
            runAsUser: 0
            runAsGroup: 0

        controllers:
          main:
            strategy: RollingUpdate

            labels:
              app.openshift.io/runtime: nodejs

            serviceAccount:
              name: bracket-frontend

            containers:
              main:
                image:
                  repository: ghcr.io/evroon/bracket-frontend
                  tag: v2.2.2
                  pullPolicy: IfNotPresent

                # command: "/app/custom-scripts/docker-entrypoint.sh"
                # args: []

                env:
                  - name: NODE_ENV
                    value: production
                  - name: NEXT_PUBLIC_API_BASE_URL
                    value: https://bracket-api.apps.ocp.kounex.com

        serviceAccount:
          default:
            enabled: true
            labels:
              name: bracket-frontend

        # configMaps:
        #   config:
        #     enabled: true
        #     data: 
        #       .env: |-
        #         NEXT_PUBLIC_API_BASE_URL=https://api.bracket.apps.ocp.kounex.com
        #         FOO=BAR
        #       docker-entrypoint.sh: |-
        #         #!/bin/bash
        #         cp /app/custom-scripts/.env /app

        #         exec "yarn" "start"

        # persistence:
        #   config:
        #     name: bracket-frontend-config
        #     type: configMap
        #     defaultMode: 0777
        #     globalMounts:
        #       - path: /app/custom-scripts

        service:
          main:
            enabled: true
            controller: main
            ports:
              http:
                port: 3000

        ingress:
          main:
            annotations:
              route.openshift.io/termination: "edge"
            hosts:
            - host: bracket.apps.ocp.kounex.com
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
                    port: http

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
