apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bracket-backend
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  destination:
    namespace: bracket
    server: https://kubernetes.default.svc
  project: bracket
  source:
    chart: app-template
    repoURL: https://bjw-s-labs.github.io/helm-charts
    targetRevision: 4.2.0
    helm:
      values: |-

        # defaultPodOptions:
        #   annotations:
        #     openshift.io/required-scc: anyuid

        controllers:
          main:
            strategy: RollingUpdate

            labels:
              app.openshift.io/runtime: nodejs

            annotations:
              openshift.io/required-scc: anyuid

            serviceAccount:
              name: bracket-backend

            containers:
              main:
                image:
                  repository: ghcr.io/evroon/bracket-backend
                  tag: v2.2.2
                  pullPolicy: IfNotPresent

                env:
                  - name: ENVIRONMENT
                    value: PRODUCTION
                  - name: PG_DSN
                    value: postgresql://bracket_prod:bracket_prod@bracket-db-postgresql:5432/bracket_prod
                  - name: CORS_ORIGIN_REGEX
                    value: https://*\.kounex\.com
                  - name: JWT_SECRET
                    value: f0e050bb786b8b10fc1abc9efbd0cd5e6b69f739011714b46c4224ee30c80af5
                  - name: ALLOW_INSECURE_HTTP_SSO
                    value: false
                  - name: ADMIN_EMAIL
                    valueFrom:
                      secretKeyRef:
                        name: bracket-admin
                        key: ADMIN_EMAIL
                  - name: ADMIN_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: bracket-admin
                        key: ADMIN_PASSWORD
                        
        serviceAccount:
          default:
            enabled: true
            labels:
              name: bracket-backend

        persistence:
          data:
            enabled: true
            storageClass: lvms-vg1
            accessMode: ReadWriteOnce
            size: 5Gi
            globalMounts:
              - path: /usr/app/backend/static

        service:
          main:
            enabled: true
            controller: main
            ports:
              http:
                port: 8400

        ingress:
          main:
            annotations:
              route.openshift.io/termination: "edge"
            hosts:
            - host: bracket-api.apps.ocp.kounex.com
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
                    port: http

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
