apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bracket-frontend
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  destination:
    namespace: bracket
    server: https://kubernetes.default.svc
  project: bracket
  source:
    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 3.0.4
    helm:
      values: |-

        controllers:
          main:
            strategy: RollingUpdate

            # annotations:
            #   openshift.io/required-scc: anyuid

            labels:
              app.openshift.io/runtime: nodejs

            containers:
              main:
                image:
                  repository: ghcr.io/evroon/bracket-frontend
                  tag: v2.2.2
                  pullPolicy: IfNotPresent

                command: "/app/custom-scripts/docker-entrypoint.sh"
                args: []

                env:
                  - name: NODE_ENV
                    value: production
                  # - name: NEXT_PUBLIC_API_BASE_URL
                  #   value: https://api.bracket.apps.ocp.kounex.com

        configMaps: 
          lol:
            enabled: true
            data: 
              .env: |-
                NEXT_PUBLIC_API_BASE_URL=/api
              docker-entrypoint.sh: |-
                #!/bin/bash
                cp /app/custom-scripts/.env /app

                exec "yarn" "start"

        persistence:
          config:
            name: bracket-frontend-lol
            type: configMap
            globalMounts:
              - path: /app/custom-scripts

        service:
          main:
            enabled: true
            controller: main
            ports:
              http:
                port: 3000

        ingress:
          main:
            annotations:
              route.openshift.io/termination: "edge"
            hosts:
            - host: bracket.apps.ocp.kounex.com
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
                    port: http

        serviceAccount:
          create: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
