apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bracket-postgresql
  namespace: bracket
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: bracket-postgresql
  data:
    - secretKey: password
      remoteRef:
        key: BRACKET_PASSWORD
    - secretKey: postgres-password
      remoteRef:
        key: BRACKET_POSTGRES_PASSWORD