apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bracket-admin
  namespace: bracket
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: bracket-admin
  data:
    - secretKey: ADMIN_EMAIL
      remoteRef:
        key: BRACKET_ADMIN_EMAIL
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: BRACKET_ADMIN_PASSWORD