kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-to-scc-anyuid-db
  namespace: bracket
  annotations:
    argocd.argoproj.io/sync-wave: '230'
subjects:
  - kind: ServiceAccount
    name: bracket-db
roleRef:
  kind: Role
  name: scc-anyuid
  apiGroup: rbac.authorization.k8s.io
