apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  project: gitea
  source:
    chart: gitea
    repoURL: https://dl.gitea.com/charts
    targetRevision: 10.3.0
    helm:
      values: |-

        gitea:
          config:
            APP_NAME: "Gitea: With a cup of tea."
            repository:
              ROOT: "~/gitea-repositories"
            admin:
              existingSecret: gitea-admin
            server:
              LFS_START_SERVER: true

        ingress:
          enabled: true
          annotations:
            route.openshift.io/termination: "edge"
          hosts:
            - host: gitea.apps.ocp.kounex.com
              paths:
                - path: /
                  pathType: Prefix

        serviceAccount:
          create: true

  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
      - CreateNamespace=true
