apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin
  namespace: gitea
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: gitea-admin
  data:
    - secretKey: username
      remoteRef:
        key: GITEA_ADMIN_USERNAME
    - secretKey: password
      remoteRef:
        key: GITEA_ADMIN_PASSWORD