apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-admin-password
  namespace: muse
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: gitea-admin-password
  data:
    - secretKey: GITEA_ADMIN_PASSWORD
      remoteRef:
        key: GITEA_ADMIN_PASSWORD