apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '200'
spec:
  project: apps
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: manifests/apps/github-runner/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  ignoreDifferences:
    - kind: Namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - RespectIgnoreDifferences=true
