apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  labels:
    app: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
        - name: chrome
          image: ghcr.io/browserless/chromium:latest
          env:
            - name: CONCURRENT
              value: "10"
            - name: EXIT_ON_HEALTH_FAILURE
              value: "true"
            - name: PRE_REQUEST_HEALTH_CHECK
              value: "true"
            - name: TIMEOUT
              value: "10000"
            - name: TOKEN
              value: chrome_token
            - name: PORT
              value: 9002
          ports:
            - containerPort: 9002
      restartPolicy: Always
