apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connectware
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: connectware
  destination:
    namespace: connectware
    server: 'https://kubernetes.default.svc'
  source:
    chart: connectware
    repoURL: https://charts.kounex.com
    targetRevision: 0.0.2
    helm:
      releaseName: connectware
      parameters:
        - name: global.image.version
          value: 1.1.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
