apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connectware
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: connectware
  destination:
    namespace: connectware
    server: 'https://kubernetes.default.svc'
  source:
    chart: connectware
    repoURL: https://repository.cybus.io/repository/connectware-helm
    targetRevision: 1.2.0-1
    helm:
      releaseName: connectware
      values: |
        licenseKey:
          valueFrom:
              secretKeyRef:
                name: connectware-license-key
                key: licenseKey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
