apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-project.yml

  - application.yml

  - sealed-secrets-image-pull-secret.yml
  - sealed-secrets-license.key.yml

  - role.yml
  - role-binding-cybus-broker.yml
  - role-binding-default.yml
