kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-cybus-broker-to-scc-anyuid
  namespace: connectware
  annotations:
    argocd.argoproj.io/sync-wave: '230'
subjects:
  - kind: ServiceAccount
    name: cybus-broker-cluster
roleRef:
  kind: Role
  name: scc-anyuid
  apiGroup: rbac.authorization.k8s.io
