apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cybus-docker-registry
  namespace: connectware
  annotations:
    argocd.argoproj.io/sync-wave: '230'
spec:
  encryptedData:
    .dockerconfigjson: AgCHMUhiHIhTbIUzfE5g006MQGHqEDV7z+ZC0Mk4WZETccFvmrmfx+leb5heONEKRBIHuulwd6CvRblFl+mi+f/BlTQYbJl7ALf/ILpu8pt8CVwP6MNoHvEVp1C8+mWdgnGbsXApovc2yTuNyhivzjEHMAzBZ4spwjNilyUzZpQGyUzgKIoi7LrPX/m0mqJqdlqlbFCGDlT9tx/oAbpKfqRp6kqleMZv6+BfqdRuKg/BV9B1dJBF0tYLDbIx6GGQ6kqRkF4rAwu0yT3YMYkewtbgia2lrikdstcL1F6CcUA887Z6vBRYuRQSOIggjOIXrKDgKWBKVkHxFiJG+v835/G08GTpeGEztnm/TkNy5ofUsiMBxy91eqpVpi41kUErZF1o/yBy9zwpp3bQ50WGwGp3RdRgJMA1h1rs6O7WByQyjdiWB3KVEBstn/KxDaICXkiD8N/1u0iOjf9cnh8VLQRJImMCIKwSQ4wGwudQ2CNvtRsHBddM4+YjQmlF61R67Qxt06d2a9RgI2tGnXuO/MKKjNJNtwFWTq7eIdWCqVEmlqOqoBQvM5ybs8gECVw+j3onvm33JFXCOAuvFHigIe9lTdfQh32CZ/4aWQv+kdxU7BQhN0ovjucnrjxoPv+tMMfoeQaGsubSAVksG+JVD7ExbPeYCo4oG+W5mjoewA51NyuhBD7Rj8T/c06sKW644pweGw4k7Tshu4bCHrlZ2TPYmZDWRpYnPuuuoB0ceFoCa5um6oSZGE3CQER4nY3d5mpl6hfzlLMllp4slXTgpzDheeCT+fH5wVon7zek0Rq76yDv7IVPVpRfSQbpbDavpABpTbiBHdItSePD4JejNhjo6ecx+/JpJpoYsFbkCetmFsMqnhzGmaQcneDBenYaoMcmPpgiOLgMe2P+uWsre9eNGL+oH39nQXJHbDFG
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: connectware
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: cybus-docker-registry
        app.kubernetes.io/part-of: connectware
      name: cybus-docker-registry
      namespace: connectware
    type: kubernetes.io/dockerconfigjson
