apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: connectware-license-key
  namespace: connectware
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  encryptedData:
    licenseKey: AgDSJ1IFN6JxnJAYqcQOvOKilywV7y75pFob2pTRFJcyiRAP2xczm87SHBn43KwUEorx1iKuqGekSqYy/sXpwSSiBOsp1rt49coIMWA+rjMHqDVYhB8XpSmT7Qy0KUGPSnOsj0GkaTP3FcuJyU80gdLJVHtXZNzEAbb6xCbEolWICp1bT2fPlJ0iyOrfYMIDdu6cwsa8hVhUiDx+fkKC60snxr/RqgTiVDnop9ia7+VF1EmU7Wh5dbZAZooHEcvw/5AvafzghOSM9btZvFIhxedKAwTjPjK8gzAKy5IWe6kVfhsxGAXebw3kl+PpEhBQx3bu4ncAiivmRb57d4vQHZqTB4LixYgnxUV0ohEoxcNaLOxn67Xv6MSaqYOTajggXXmy/gh0a5twqSfklt0Q0Je2KLKqc4doRpjX8JXqlM1LsrS0JuVL89wnLAuf+Dcz9X1q3J4C0jdU6QnXCTw5hSFqM604CaX+hWq6BU+Dp4EaWtNf8H69pMqhEx3ulgW5NA+DwbMWszXZsZ86afpEk8xTPizjqkuevD4cH6hzxePUa817+7/01Ndp76KT3UvxxL5Z0QiBDLaO/BPwaEyALuxw22e31rQFsZUldvfr6ifFQaOpJrur9cG8N+rovT01jMlMfQpU7TGJ2/t3dABzin+Kl+akuZajyBi32qLQkkJVgqXH1Bedgv/brtjDkRZONQA7gsxS39Bpml5uvOL1Zw7l7Dt1CNPbptLi
  template:
    metadata:
      name: connectware-license-key
      namespace: connectware
    type: Opaque
