apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nayris-server
spec:
  destination:
    namespace: nayris
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: manifests/apps/nayris/apps/server/overlays/kounex-ocp
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      
    syncOptions:
      - RespectIgnoreDifferences=true
