apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nayris-client
spec:
  project: apps
  source:
    path: manifests/apps/nayris/apps/client/overlays/kounex-ocp
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: nayris
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
