apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: github-runner
  namespace: github-runner
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
