apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-runner
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  project: github-runner
  source:
    chart: actions-runner-controller
    repoURL: https://actions-runner-controller.github.io/actions-runner-controller
    targetRevision: 0.23.7
    helm:
      releaseName: actions-runner-controller
      parameters:
        - name: 'authSecret.create'
          value: 'false'
      values: |
        Args:
          - '--update-status'
          - '--wait actions-runner-controller actions-runner-controller/actions-runner-controller'
        readinessProbe:
          initialDelaySeconds: 10
        podSecurityContext:
          fsGroup:
        containerSecurityContext:
          runAsUser:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: github-runner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
