apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-runner
  annotations:
    argocd.argoproj.io/sync-wave: '230'
spec:
  encryptedData:
    github_token: AgBDKwu8KIumI/AnBEq8l2Zis2JgbHoqkwLA035LRXUJFwK/p+dtOACTElEu5z+9zi0mzjqgxVvw0yM2dlFcQHbNC1wc94E6Zl4HAOLRPyyPoj67wlV3c7wtbn/HVj3cqwr3wTGXhSLIf+hOUKnKsnSe3S4H94YRqY6XceRO6MfSWJr8ygXrqNZDmF2QDcIa+PkQWGjBIUUCHsg6C+8+tQCjuoWagi0tI1Q9VLAAkKhymC036a2IhyETBDQg5Gs6IZOMunE2v/dtYqAHrF4X20b6e1zZ1yh8iE9BW6OxC/kxb5JxEsn6X1qjDFmXEiVCmegsSodfNO/O3qK8s5doEzDMdNV4n0NnoDpoaGvyRLNOLQScqTCTKL19OmzSVcJ0zkrHAjMXDV4BsAtDGrcY2qatC2WQj9sLzQOU0qOFJ2vtsGgf2Fxho+P4xxxX1jSpmkIMeVO9pxC011DSk2YFwoCDk0GYzkrqf8Ge68gI4pcTelwZ7BbL23G0APwDaTzna5oB1PGVayd2JbbvYEce3Hm/Ui+k+eiFv0/BijiM3ieagb69IoF8zoTqRaaNo9369tN7Qd689+8RGygH8WBHnQh4Wv2lsrB8cQdZqN2Q2vIn4JKay566W4QNkf4K2u2bmNE3BIrKjhrprPp7BLAAwV8z43Ry4+ZJxSoOLfHHeqy0cBmmApjx2jg3sXUjiBbliGhepkvO3xHegmWfpD3RS3n+78yL8i2ROnDbQUIpaf29O4u4Zr5prB33
  template:
    metadata:
      name: controller-manager
      namespace: github-runner
    type: Opaque
