apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-runner
spec:
  encryptedData:
    github_token: AgB8r45U5YXbHXP1NcDDgB4Yqa4Ab6c7n5kSzAHGa6LnK8bJTF+oucaXcDl3RxS6hoTaMpjCrk2alw8/necqIqVZlHns+PTkEp4cmtMGJ/TvCvL1IV4SWesz7ytIbthKWSyhmhek5gSRUPQrLsF2hVyswNFKrmCCzzsC3aSaEdeGub3R64OfelVALW0QqSDt2ELdk5KjuErgtl4YE2u906oVVhSohorD1EheZebdgWhix2vn6emaDWHFkwaS7l6ASp31OjMpJH/RYLanHmk8+tKuHlXECycFx6WmVDY7qDiRWZh7Unm3JKEKYV98I1ouP1H1cKiCleUiJEBjrF6CSXoah5XEvjBl8SNTba15id7kGlUuDCnJadoX8D8XnRm39sehu6zep9D5qrUCHMVd/mqKpL6Wkbxr7RseIUomhaScfuMTgjsBS0vZ1QBWi99+aR5iSZngyi8es+Y1kvXD04EFFS5rRSBBKfMOAqFNTl+q+lvDTLBhmWXmCnjOta2RXxx9qAc26cnGqg/5+c7QVX/0VxLuOKUCsspMuqtaxJmKMo+vacyXnwmru2GImlr2OP8Xj9h1465nfMjWQNcC7AU72Z/COsYZTsz6G0gbN6avpNGpNhXsKpnKE1kSzXtBO7G9DKgTXZYXBF+90XklA9HiKkpj7obO6uXYaMyewle3ciMPz5XrS9hDSJE6FWg4f/anqHtLoaKSloKN0/ovTw5AvZPSFrg9vm4iHBdsB0gQm5eKKi0F46PW
  template:
    metadata:
      name: controller-manager
      namespace: github-runner
    type: Opaque
