apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-runner
spec:
  encryptedData:
    github_token: AgBvqdxUYnLu+P/SoE4d1ioXCkpHnYrKtUE1YIG5sWbs1u0U+GpuHkb6cO2QcCAoxMqWcv0zpCu49nUlzkO2zYkJ5UW0Bc5NemFK9ggNaXWleh39xrQpr7nNqDMz8+7N9VdvNVsHAZqbf6XkLwM7HVSHhcJsWHUL+ae5dBJ97NACEzFroUMLbaL81ru3qgTkt61sJ4B/MEFdqT1OftGSfhtS6Nu9T1fUGjPWdNACXv8B/MiKrYtg/OM+W4YXysUpLoCICDv/Z+CXE487TLc+0d28GGAYh51TuOY4GTUztKXPQC1coy3X0n+b5YtcrdcE/BWEEmqO6kzFqBtcR92+hBJ+lgtiz7UeFsaH8We5zjUVQ3XmLyL0uCfCzBdNunD8OBqOa5DJLRvfrKgSj+p+6q2vJOygRpeWYZTbZABFFfUeaDizCkE9h2Lb9ntPHZb/CDH5b6xrxFMXTMJHwSjLRDUgLyzGjUxEwpk65ZMgqRbKOsuMuw7o9szYG8N5/qroDO4aXikEYJXV+5J/BPolrRf1dtsHikp0vBW1GjnPDbtIBXpyYGMVG60bkQu4VLPdmn2oZi8IwUe8f+tNJVgrJ7/3Av8W4mdPtiGptFpW2KTBlDDzxfD495w8g9G4ktUn51HMyi20Ki/oisaXumPhvqkZaclycZRKemsoPz5HxFrcZ23+EKFDf1oMnqZS9+UkIGvs99QFmQc7DgJOLv9WJ4n84++IWsod4TuVGya05F/qBmzTbi9ESwPO
  template:
    metadata:
      name: controller-manager
      namespace: github-runner
    type: Opaque
