apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: controller-manager
  namespace: github-runner
spec:
  encryptedData:
    github_token: AgA1VrMq1sNndD6H/IObjUqKc86GUSt5/qZVcKbe+0EMr/rUiATmx3pxPOoa7XVqLN2zEkv9dRs5joZqf2vUnZ8GFS180o2yLy2N/BnGQ1jYSWsP4v+x4vULaJCGZkDA/MDVg4H2ysLuxFKmnFuBSsZw8wZibtJ4SQE/wig8aQW/TRBOftM/AP3ErAMbMvAUxB/QLTzA0l9FounB4wliIkOlCwOGvnR1iJrCgiL3I8QGhQzE7rRCpqEFGuwUovXWHfCxW5AoosnCrUQDKighsDvGCHoMsT147sH9at82AHnKffZ1gfbn6Kd+4k5pVOHOHCA2OjSsQw82GvopJJ9G89wBsUtEEsJZWy3lobAIPwYX621cdeaOc577ETJ5ysnpsBSYmeb7lq/Om/k16HddfpMQ+UwlvDbV2Pfr+8MaVsYSiDAY4CM63IBXILvWXpfHBFIF5zWRmxD0bjKVMffTooGVX5BuyNRq7FD1yXCxX7HdsKOHWBhbJXljqIyGaFBP4JxXz222n7g16aqna8vHAtmmxLUGfGcRBQ656cRhEqq4+xcC2a/h3PsgtMNJMBpKyfuOaPyAttgn2Rc7W249xE2ivBQF7dPX+iwFaTA33JHFauLUNqie1Q8UIK6HGr91co8Dx3AbZR5xfBRjNu3F3AjtIwqj17YL/xHXctk2JMmyB8Duks2tw34u7/P+eGJI/JupdUjdM0bY3pdqH6M95FFYfTWiRVmsFbasDEwOPgWIuTWThKG+Pi9E
  template:
    metadata:
      name: controller-manager
      namespace: github-runner
    type: Opaque
