apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluespice-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '200'
spec:
  project: apps
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: manifests/apps/bluespice/apps/overlays/prod
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  ignoreDifferences:
    - kind: Namespace
    - group: batch
      kind: Job
      jsonPointers:
        - /spec/selector
        - /spec/template/metadata/labels
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.spec.volumeMode
        - .spec.volumeClaimTemplates[]?.status
    - group: external-secrets.io
      kind: ExternalSecret
      jqPathExpressions:
        - .spec.data[]?.remoteRef.conversionStrategy
        - .spec.data[]?.remoteRef.decodingStrategy
        - .spec.data[]?.remoteRef.metadataPolicy
        - .spec.refreshInterval
        - .spec.target.creationPolicy
        - .spec.target.deletionPolicy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 3m
