kind: LVMCluster
apiVersion: lvm.topolvm.io/v1alpha1
metadata:
  name: test-lvmcluster
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: '15'
spec:
  storage:
    deviceClasses:
      - name: vg1
        thinPoolConfig:
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90