apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reactive-resume-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '200'
spec:
  project: apps
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: manifests/apps/reactive-resume/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
