apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sharry-credentials
  namespace: sharry
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: sharry-credentials
  data:
    - secretKey: admin-password
      remoteRef:
        key: SHARRY_ADMIN_PASSWORD
    - secretKey: client-secret
      remoteRef:
        key: SHARRY_CLIENT_SECRET
    - secretKey: invite-password
      remoteRef:
        key: SHARRY_INVITE_PASSWORD
    - secretKey: smtp-username
      remoteRef:
        key: SHARRY_SMTP_USERNAME
    - secretKey: smtp-password
      remoteRef:
        key: SHARRY_SMTP_PASSWORD