apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sharry-postgresql
  namespace: sharry
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  encryptedData:
    password: AgBPB5xd9L4JSYY4Z2h7FcrqMLECZNw3lRVxuoCh//iMeZCmECjZCUtZMdB9Cyvlc7UN6o9J1L22V5b495n5GVXzUuuKD7Bv98gNgoaOFLGB7ugcc1+K4+671ztxe0BI6ZxwNUvqMtzh72aObgeQ3Mdp0WCNCWipPCRWt9uqwTCjtPojYrAO0qZ2l/hPdD/KZ6dVpCgonYVys5TmLlx+ynv8gdNCs2uTtRcKoat9ASdUcSPhG8iuVWt4F/Npo7wjmrwTXjhh+pXPGfGXkeRbPyLMVwOtMf550/egGyx9JiQpKDGmHIpt/IAhIpjjC2LLGb/sgMbiv9W8gNsjKd4ixAcj7TGym2UXTHFHILD5/oaUyNDyAA4noKeZYlllPtnYje/Ar8l5YiJmUQAgW0s5fL8Qkg3UPtO1n8vj3ElWPumGe9/0ppib4E1OAFCqTda3w6pHrTw4kr7KOYx1KmlMte4GpByfD/uYaiuI70TWw7ZlzvvcKRoaGWimDn891Qav3TpzRWgzxVN7AQ0G5f0am2iDlXR4NrkWpCgnq809xwWy0H+AQC3mrxc6f6us8JDyas7NHO//kWL7rD+3fSEHiKhJoBkG3oe2eUdqhuR/MfLvg9d2qebA3i+vn/ePXt11J6TH3DrtGqb9LHzEwv6ZOJBqXflbK4uMbSJQFwU8/w2jUg9hTxub+ni92ecIjaWqJU/cnBimWhsS6mfD
    postgres-password: AgCFHkGn3LMPi1mj8h0vN5qSYTa+2+Cr/6eegOFvwV69sfTVWKCYN75uAk/0G3Y1+haXruQvntCysW4fdnJJ+T9kBqyBtp916o3bCpfY4XXobkz2tfwo9dpizKQ/FSeN3JYKv2KeSU6PDxGJVkkzXbsM8QPAWoq1H2pc8hassYxEhgoCja74/qr1j0scbJxKMxiiOjpsf4qe4jVXGZgNUHQ4ucgCTgIdzWtsmviKOHjwZj77cPLFUuHk5/aicSPE+iRyBPRaXj1oZd7zU5rUJ1zT83FcjBRnLmefSPLK7Ans88IGwfEVMFUIq64i06PSqgLzhk222EEeIhZzexw3/RLekehRhkmCgwygNQdOC83bAZoMWU/SKJ3CBJtKbqbtWPeNulfUiVtl3c6eZ/WgjjLQfHg+0P+q238VEkMG5bU76QHfTuOGh6DQEtyGaAKbHIFJ9vWDyYHLS14XXQfLm5T1GfBqpgIY0x2PgJtTsYx81prRViV6WJuXFrbIyF88Xu+GHLaPJz16ND7bZdg2Wf6G1cbpISOW8+T/Dhp13RhpyfLb1Jwar5oCvawy4PoeTk6ikQsnPHAuaxNxP9a0v2h3/mvM+p/7m+gqak0cIXbPz+5c6EQ7ogNtHS5dQVwwx5zDmo7mpQaiNYkHTClf+QXer3JV3y5DVWfTYbcxqrZ2BWn6ty3Qa42coMwcYaZ80qNTF9f7n1+dd/9c
  template:
    metadata:
      name: sharry-postgresql
      namespace: sharry
    type: Opaque
