apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sharry-postgresql
  namespace: sharry
  annotations:
    argocd.argoproj.io/sync-wave: '230'
spec:
  encryptedData:
    password: AgAgGySI0sFtrb5Pr6MireOFF2czgyonp8t89eFrhxyEsrondZtKSqvt8Oi/ZThnAGQXy/5nFIgFCDieq38ahc2wX/V6KsiCa+7zG00YVQL/iEUbA4Kz1SkXVjSOWgjYtmDnm+oaFghJX/ybvjBY8GVRqhw0fafluFX11Uu1NW+VQJj/+orTBG/YwBDmWmQWTZaZc+E9pXUlMMVw1BMbUdu2ie2Ueety8zfnuz+l47kW6zjdocLlngaLKzcfRr5T4UqKRGLy4QxvXEh+VAZ5y3jmGuCJb6CAWZOpvE2ng3EhlbMY2ZhltR8tpiA9fV1voPbMYkIm2mTMM5z+miLXaDxuWK05HXrX3+2SWEXxbP/cFUov8syNFo5/w/wUSzfOVWekCctTgyLU55kcQ1mdwQEAA6ebbJEHbtElOhOAZyOAQZ4lILqKz5vLGGd2lv4aLfKvQUl2gSSham1KGfapwebUMIt9ljDOOS4bLeozyp8GxjvzGdkMSl+zO68xUt8qYyznuOWRPHfmVtjaEgarH/kcXsCX8LQy/PK/1XDniAgFTqDEcYaZRnq9RUo+WtcpVgk/BLXUsEZTV8Brx6nFN/eIvRZ9ORONLSiSI2zYXCi1ByQIVbRwaRh0LL7CsbgKF7C6SRkJHFfDvR+amnXJA1dz82RnfY2SW3AbJ/jyxig8nyJa/kaEfyVFETWZ0LjlSUXRLa7cGpTztZep
    postgres-password: AgAKoeyAgCkHRTvrK7yePF/ZYJ4phTqC8P6fzetzvFu/oviR8lPyEzwoIxeN5WA54/iT/C9UeFxnb0WkBgWDPEZHgoZXmnaQXse1AkcIfV+d3oJX8vw9Qu+Yp0lz3s4tOLOKGEBUxfk7GD/vTZM1A6sdXMOwK7/cg2h4A38nLTb1FAqVr0MhIGfG5nhuotY3sWNe8vtHZ6z0uwhqn9gNoCXkFBrZcmnPKarNgEWjz5l6bOwXTZBy0Tr2FYN/4kMWvAq1DZKwZqMVEqrlWiR9CO+w42tSy4rO4WTKId9Pbt7Jk0flTvqm019qKDBt3ttM5y+aDyIYrytSAr8AxMzy/I6AFgqbPOB6E3ZAVKup/U/IB9Q5YBnvPZe2x0QoWmI54mdjxOnGRmS1MxKNTEjcXrhT27ve29VyRBcqVu++QFnijJEYctP8df1G1L8yQQXzWu2cznmRmb8LEJqSMb6xgaNC0ceoC3BJ24Y+KcCxFVXMrB+n6zMzQFFBot8RPvGy5iHCZ4CnJQ1l56p93u2ndW3QBJmgsNuU3BQm16WIws1OvdmJYmiuQWxZol8MyqafWgJ2/qLR1d+//bJ2yttjvq/LwEgENteDHNvLolsKcQd0MKffS6Kc8ZmPZTvpGoLf+lvM7vvH+n2J8DOqiybJNNohhLzDPN+ZLB/FNhq6qOxfghOkfhKjJ9zhTYseIrJEAGPS2judmZ8w4hi1
  template:
    metadata:
      name: sharry-postgresql
      namespace: sharry
    type: Opaque
