apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: update-day-api-keys
  namespace: update-day
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: update-day-api-keys
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: DISCORD_TOKEN_UPDATE_DAY