apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-visual-inspection-ui-app
spec:
  project: apps
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: manifests/apps/manuela-visual-inspection-ui/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
