apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muse
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  destination:
    namespace: muse
    server: https://kubernetes.default.svc
  project: muse
  source:
    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 3.0.4
    helm:
      values: |-

        controllers:
          main:
            strategy: RollingUpdate

            labels:
              app.openshift.io/runtime: nodejs

            containers:
              main:
                image:
                  repository: ghcr.io/museofficial/muse
                  tag: 5bf5547cd1fc7cc90a2e34e1c569d91bff47da51
                  pullPolicy: IfNotPresent

                env:
                  - name: DISCORD_TOKEN
                    valueFrom:
                      secretKeyRef:
                        name: muse-api-keys
                        key: DISCORD_TOKEN
                  - name: DATA_DIR
                    value: ./data
                  - name: YOUTUBE_API_KEY
                    valueFrom:
                      secretKeyRef:
                        name: muse-api-keys
                        key: YOUTUBE_API_KEY
                  - name: SPOTIFY_CLIENT_ID
                    valueFrom:
                      secretKeyRef:
                        name: muse-api-keys
                        key: SPOTIFY_CLIENT_ID
                  - name: SPOTIFY_CLIENT_SECRET
                    valueFrom:
                      secretKeyRef:
                        name: muse-api-keys
                        key: SPOTIFY_CLIENT_SECRET

        service:
          main:
            enabled: false
            controller: main
            ports:
              http:
                port: 8989

        serviceAccount:
          create: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
