apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: muse-api-keys
  namespace: muse
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: muse-api-keys
  data:
    - secretKey: DISCORD_TOKEN
      remoteRef:
        key: DISCORD_TOKEN_MUSE
    - secretKey: SPOTIFY_CLIENT_ID
      remoteRef:
        key: SPOTIFY_CLIENT_ID
    - secretKey: SPOTIFY_CLIENT_SECRET
      remoteRef:
        key: SPOTIFY_CLIENT_SECRET
    - secretKey: YOUTUBE_API_KEY
      remoteRef:
        key: YOUTUBE_API_KEY