kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sa-to-scc-anyuid
  namespace: muse
  annotations:
    argocd.argoproj.io/sync-wave: '10'
subjects:
  - kind: ServiceAccount
    name: muse
roleRef:
  kind: Role
  name: scc-anyuid
  apiGroup: rbac.authorization.k8s.io
