apiVersion: v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: serverpod-test
spec:
  containers:
    - env:
        - name: POSTGRES_DB
          value: projectname
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
      image: postgres:14.1
      name: postgres
      ports:
        - containerPort: 5432
          hostPort: 5432
          protocol: TCP
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: projectname-data
  restartPolicy: OnFailure
  volumes:
    - name: projectname-data
      persistentVolumeClaim:
        claimName: projectname-data
