kind: Kustomization

namespace: serverpod-test

resources:
  - namespace.yml

  - service-account.yml
  - role-binding.yml

  - pvc.yml

  - service-postgres.yml
  - service-serverpod.yml

  - deployment-postgres.yml
  - deployment-serverpod.yml