apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-app
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  source:
    path: manifests/configs/auth/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: configs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
