apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: htpasswd
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBS4hxKmGYymBKeWtGKVteFUHRI/6ue4lWNWssd6ZLU0Drn9foBYMY5N8Tu0KdswnIvXHVeZKRIblEIzqMVTrosh+nrqgQevtkzv2XFxcIPQoY0ZEoICknyiizDA0EAYDhkIsXfMBGmkgwmSHiegOGuiXu4Oep3A+lC+8a8NOcuRS4MHP7tpbBurhgLMeXuZv1B4yg9KkA1pIyVFi/bpqz3uoiMiQzxdDZ2u8UwAT3y1Xex62dqrN/Njdbm2OIwgOxUZblcqYdiXfWFYcfEKEkdYcchxxODa2QBSWvoMVplvJnZpn1UDQyLplcMCSA9wDY0SKpsakcZYOb2KExef3MY+ku+fRaU0MGrEI5CA6J7Eig19IorddkOsdxWPHXbd6qMNKh1XDvdnzPM1uXs9CVXw4jj3qQoPM3tVqHJhoSFcR8k7IATMFynfItDvpeQrF8IWK9/X9bjTgiUA8hM/PxXVV3mPHBkr8J5BACbom8Qcqx4/RwyvaprYOUF9wfQulKUUc5tG+T5AFrzcPnYD0OXjf4vBNi6BKEP+hw1rXKlJA/6R+aAzhngBzHrvdmC6Q/2jun+RoqUGSH1LqVsp9ybwZ8OA/Am/eYTi+mp+qVtCVVejR5Dx6NeE9QWAKVzdf0tl8EZriSzk4fS3TTkGI2haGJcGtnOB3OJJfftuoTobL3B6LZDTXxITFWn89vVabXAqT8UsDkBEGfI19MnWKJjTqjEOZt4O48+I223DGyzes8hbXh1dDEawXIGtJuyFI3snpkqJGciy72eilghq1cJGgvt
  template:
    metadata:
      name: htpasswd
      namespace: openshift-config
    type: Opaque
