apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/reduce-resources.yaml
  - path: patches/dev-config.yaml
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: wiki
    patch: |
      - op: replace
        path: /spec/host
        value: wiki-dev.apps.example.com
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: wire
    patch: |
      - op: replace
        path: /spec/host
        value: wiki-dev.apps.example.com
  - target:
      group: route.openshift.io
      version: v1
      kind: Route
      name: diagram
    patch: |
      - op: replace
        path: /spec/host
        value: wiki-dev.apps.example.com
