apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configs-manager
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: configs
  source:
    path: manifests/configs
    repoURL: https://github.com/Kounex/ocp-gitops
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      
