apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-config-manager
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: gitops-config
  source:
    path: manifests/configs
    repoURL: https://github.com/Kounex/ocp-gitops
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
