apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: set-allocatable
  annotations:
    argocd.argoproj.io/sync-wave: '10'
spec:
  machineConfigPoolSelector:
    matchLabels:
      pools.operator.machineconfiguration.openshift.io/master: ''
  kubeletConfig:
    systemReserved:
      cpu: 500m
      memory: 1512Mi
