apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - app-project-gitops-configs.yml
  - app-project-gitops-apps.yml
  - application-configs-manager.yml
  - application-apps-manager.yml
