apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kublet-config.yml

  - crb-custom-cluster-admins.yml
  - group-cluster-admins.yml

  - crbs/gitops-crd.yml

  - argocd/app-project-gitops-configs.yml
  - argocd/app-project-gitops-apps.yml
  - argocd/application-configs-manager.yml
  - argocd/application-apps-manager.yml
