apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - group-cluster-admins.yml
  - patch-gitops-edge.yml

  - auth/sealed-secret-htpasswd.yml
  - auth/oauth.yml

  - crbs/gitops-crd.yml

  - argocd/app-project-gitops-configs.yml
  - argocd/app-project-gitops-apps.yml
  - argocd/application-configs-manager.yml
  - argocd/application-apps-manager.yml
