apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - group-cluster-admins.yml
  - cluster-role-gitops-crd.yml
  - crb-gitops-crd.yml
  - app-project-gitops-configs.yml
  - app-project-gitops-apps.yml
  - application-configs-manager.yml
  - application-apps-manager.yml
