apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler
  annotations:
    argocd.argoproj.io/sync-wave: '140'
spec:
  provider:
    doppler:
      auth:
        secretRef:
          token:
            name: doppler-token
            key: token
            namespace: openshift-operators