apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/display-name: Red Hat Certificate Manager Operator
  labels:
    openshift.io/cluster-monitoring: 'true'
  annotations:
    argocd.argoproj.io/sync-wave: '140'
  name: openshift-cert-manager
