apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: '120'
spec:
  source:
    path: manifests/configs/cert-manager/apps/operator
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: cert-manager-operator
    server: https://kubernetes.default.svc
  project: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
