apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-certificates
spec:
  source:
    path: manifests/configs/cert-manager/apps/certificates
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: openshift-cert-manager
    server: https://kubernetes.default.svc
  project: configs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
