apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-issuer.yml

  - external-secret.yml

  - certificate-api.yml
  - certificate-wildcard.yml

  - api-server.yml
  - ingress-controller.yml

  - argocd.yml