apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  # - kublet-config.yml

  - argocd/app-project-configs.yml
  - argocd/application-configs-manager.yml

  - crbs/custom-cluster-admins.yml

  - groups/cluster-admins.yml
