apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: login-theme
spec:
  project: configs
  source:
    path: manifests/configs/login-theme/configs
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: openshift-configs
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
