apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: login-theme-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  project: configs
  source:
    path: manifests/configs/login-theme/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - kind: OAuth
    jsonPointers:
    - /metadata/labels
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    # Since the secrets are huge it might break the
    # metadata/annotations/last-applied-configuration length
    # but serversideapply will avoid that problem!
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    
