apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: login-theme
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  project: configs
  source:
    path: manifests/configs/login-theme/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      # - ServerSideApply=true
      - Validate=false
