apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: login-theme
spec:
  project: configs
  source:
    path: manifests/configs/login-theme/configs/overlay
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: openshift-config
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - kind: Secret
  syncPolicy:
    automated:
      prune: true
