apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpasswd
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "30"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: htpasswd
  data:
    - secretKey: htpasswd
      remoteRef:
        key: HTPASSWD