apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: htpasswd
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: '140'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    htpasswd: AgB+VuWgH6BGfRDnQTkY++P9khuLXTpm8FffWl1+oHu+4BS21zBhJizX6LfaUMPReL4cvZJcFdtx5Oz4zz+beYyxRafbi1PWUKKd9HX/lzVPkIk7yBrSrNJ9OMaYC7xT/BrSvGJMGtm3NjQwsgQWPkc9/uNHTY1jhwHgWzcxWoMO2A5LM18ffgUgt3qYd3RzVXU4vD2qxC90ZKZOYUOlMMyMg+rG7h7yS76O9C7BNUmqmquERpC3vyrD2rDw8oWnnJW2GI4HWl9huQ/AV65F43kaOamjoJ56U6oRwU6zrp/YAXWCYhAJBo8lGkNVA+Jb6mTu8bCKQdNNLEQTTNZrK9y3+8ylpc2RCLvM93bxllDeJQ/lPNtbNRFynZpq0r4+A0SQHdOw8DOuFI9h4jHAHe/xpb8CyRugsVmNqx56Qi5PqWhTVTkxKaJfLFzZ83E+LfCSg3DbPyyUiYYzUtObNwKYA0eyVWV7N0c2RGHLYanmOpfhRnylBByFx6te7zBl3ARWjotcdlwXcxiQZMcrIBYO+GTD8A0j2y09JyCmc72UynP3sGMqr82DHbFK+XqVnuJGS3HalC0XtBH3ed0AoM1Zgjkui+xJQ2aNUIyljjS5OIJ/WWbwuXmhqQu94kxzXaV9lyX3m6L0BYAvH5ahxRfZSUCEPphubDozS9ext7dbDf+kVyqCJJ2fnpJTROoMtVtmJ4dgEKuoyDWREpzEBqH12Dtd5mxhxmWWrN5rJDuwszb6XMSDXhiEqch7ZjkfcgsWD/+LeH6Fu0DXtROA1GhoweU=
  template:
    metadata:
      name: htpasswd
      namespace: openshift-config
    type: Opaque
