apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-config-manager
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: environment
    repoURL: https://github.com/Kounex/ocp-gitops
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
