apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: '140'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    api-token: AgA8EjJ/BRB/ApL949m+jl1H1111jdWgodDOnoDAnz6+1Vel4GRlctF4/cmhKXY89cxhBfzVJach+DHu4aZy+zAosqilgWZx6u5bNLdBeDEvbavZHR/wLn24zk/Oejt4QtkS02u3+e2OxZ3n/gVNlilBQjdRiMCFthhVBw6XaRm5mh3RE0CmuVni35Qx7u7KsCqqegRX+1gnx4ZMR3v9YEM0ohlHn31ZGAMc5BmTCDJP/4QSnC23b3BD/fGdFgWiP8i+ElgWGHSlPQffcjURZQbgykCmOFza560TbawNHMzjE5AJEmc23yr2ryVyJJMU2jxvrAnjJHrsy9AFQavTXt1mio+i0qR3XPwfWR7lUojBbfk0aT2jUYAGi0mRgvlnfEFAugSaT4w+CWGYoDRuB2usTUIzXa0nSM9xXmn6e+Akr7P81K5tmcgpY3c52aKdOUhr6sl7AVBR5ckF9cyVgU2raXwohFABnQV6SCElQha1wYTfMnpzTet5Qg+Mncs4thjw86bd8SB5v22Hxb1e4kcF++5skoAk6COeqjPL6hYX5b3z8Tt21txYl7bFIuxPrsBl1aFdA3ApVh84f8Iw1uIlo7m78NoU7yJUrLsNCPtLYdBP+Yb5Qr77WoxFI7LXz5APk+tqVa7IKNzo+H/pgkfMvmwHXHFAKXATZw74pKB7np7+JfBkG96M95YKkvKIc2Ih/8f2xqJcYmHHADutp4wideTs5TQfNZSS808ycEKMgdJkTNko
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager-operator
    type: Opaque
