apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager-operator
spec:
  encryptedData:
    api-token: AgAOG2OPhkqfZqtmfOoeMNT6+pYf8tjKXeVFIYWcnKRRj55hwl6QjECRHRHv+Cgv7S+zN7ZcTsI8eTEiTFIpZCwdQekfeU/TS/I6GDkeXp2Oq/kJ72Pn+tQ/Y90xa+6eKSOnhHdrbyMnQSb2tdV/X0UBWz7Q9WWlf2+KYHXaHUQi7EjVaNkaOMhYyIbZO33ZXWTy1t71w8hIc6SHLMq6edjBMTq9Zynsio+l+I8oipC+6JpagfpyZoC+g+sdelWBemX1ISOOPXCCZwEO2ap0Xvuz1mf5DJpqiCKDAb6h8JVvUDPlE2cwl/b3DMZawb8uDH8K09Nfj8bxbcL36Sx1mBW3KhmKUPK33Gfzk1E8aXfHxpuObo8PLmkl0GVl9QV9UGn4ar/S4NCSgHI7Q+eDqyf7QnIySmP5ka8VHDENR2BV3uHn6ceObOZ2ifg0tR0g4ZTw89jc7ZRg7dJWmxjBNhsBnsJLy/HK77BHTr9HBzmtls0iz535qneix4XaS8kpzpqzMvBi4WFBrOuwx19zbcHT37o8c5d0GmUjYhOcDcthL6rSecufMjqlZbvvXi9pgb5Yrw9y5E+bUZ/08MIdP0YqlJnhRMDADeGMoSv7gstSLG1gXWsI12psYdGP0fDubT7nnM01GL7vc5TH0W6oipnutOcRercWIcrlUn+OBUYTEWwdi5KK6hEVPfpo3EppTANAtMdUm4lnKlyvH8cPTQCY+Us7GJEoRTTzG/zvtRg+gbT8Do53
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager-operator
    type: Opaque
