
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: '150'
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true
spec:
  templates:
    login:
      name: login-template
    providerSelection:
      name: provider-template
