apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reactive-resume-db
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  project: reactive-resume
  destination:
    namespace: reactive-resume
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.2.8
    helm:
      values: |-

      
        global:
          storageClass: lvms-vg1
          postgresql:
            auth:
              username: reactive-resume
              existingSecret: reactive-resume-postgresql
              database: reactive-resume
        serviceAccount:
          create: true
          name: reactive-resume-db

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
