apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-project.yml

  - application-postgresql.yml
  - application-server.yml
  - application-client.yml

  - sealed-secrets-postgresql.yml
  - sealed-secrets-server.yml

  - role.yml

  - role-binding-server.yml
  - role-binding-client.yml
