apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reactive-resume

commonLabels:
  app.kubernetes.io/part-of: reactive-resume

resources:
  - app/deployment.yml
  - app/service.yml

  - chrome/deployment.yml
  - chrome/service.yml

  - minio/deployment.yml
  - minio/pvc.yml
  - minio/service.yml

  - postgres/deployment.yml
  - postgres/pvc.yml
  - postgres/service.yml

  - redis/deployment.yml
  - redis/service.yml
