apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: reactive-resume-postgresql
  namespace: reactive-resume
  annotations:
    argocd.argoproj.io/sync-wave: '230'
spec:
  encryptedData:
    password: AgCsXsP8jPBjgVOUih/Ii1AcddLi6ABrFGX4lohx/e1c4jYU6bcIbqJWy7QXv+mzuO9Yv+augU2y409dCtlc/zLlnII/Jkez/D/Z+IleS34QMq+BGgcOaeB3uDM2bPsk7jpMxrIt3ZAiDWIYktQbLrJ0YGENvDjwYjOsi8FPaHs8Ta5ZjVXTIwHaVEUq4zGrgIKNIux2yHGKevZtZGm8RFjM4fNwJrn+f3aM7eGZkykH/KWBitD3WOWjOQLPE9lWno/vd/wuYU7VUFMiYKHaVm1n5UGNWyRHxDFsghiQXph4riFPohkxdr1c2QYqlszibBd6Pzr4wI0rZxitJjNNRKW3IBEI2AJutGh/ij3NjdKfT8g8i2NWgsSqbl1AEBs7yvk8Pg8d4O/X8jXAc28vrVq0/ST1DaterepRr5SeoHpTDWZ/ZwrzfqOWigQq0yPhjqyY+cSDrEwFdo+FihgIRXS1qxqxqMM1KDZaILJdY9r5SSGQZUceM+fLr4SUdfrjT7xbshAoTemLBfiaPe0MjxaZ8wwvWVqji0EME2ban4H41Qe4ZC9jloRkgot4IJ1CDTRztJufpn3k/sqpqEAgSG20RS9wdms4ywvCjcSelkjxjsHOBAjWlSOrBmAVD9+jpl2cmoEEDmYGcdwv5gkHg1swwXAErqSkRcZkkzs9CutBhtZ7CFFrZmQOdAooglRczAb7EM36YD4w3hID
  template:
    metadata:
      name: reactive-resume-postgresql
      namespace: reactive-resume
    type: Opaque
