apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: reactive-resume-postgresql
  namespace: reactive-resume
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  encryptedData:
    password: AgDKt3MkgBEaR0h9laUzjTAa/2d/dvy/awYwefs97QUpVuV6W1giW8rgdVGrDl+XDHSqf2yWvGxfyT7zkbb9Edfvuhv8CPnWpTzBOrWzjPsoxQd12gcCDmG4gYM7UWfG8qI99Kw2h1yAC7vjQxXZqfIED+N7cjVY1qAR+aKcllFCuPBkfIuCcdtY//SjLN9j/W9IxLm63LptMT5uu1a8/G+xYr24rn7dhgqVHhdtlOpBSw0kprLflC2ZqkVYQx4952O+dqGqIzk4KUNCDmUaWhKGC/PxbKLgY9N5YNrFoeF3oSgaPtsR/PnxJsTOn56dnxCphrCAPtimGkFYoydJqMzmd/qBG30RFrfZEGr9xopLKyd7eJUF8FfBDefdtPoEdBzH3R54oZ9teiAn5FOIlPx+OKAscjU3MOTShtv9Q8L9TVOzKrhropYXqj+dMlaE31Setus62upzv5SgPK/45NSv68oBn1vy0J9lFUJanAt6RfJKeWB/7TiTbxez7bPnpO6j8VFkod7U43NG65dMAbowXxOZfH3cbU6UP1nPNn0B60tOEs0mqbL8Z/l1TtXl47D+d0Otk+PGCLvHUzx0Ks/h9Lx58TQ3F1TLAJlo/n9hRb3R+P5lmef2EiV2wz6wWAY4/uEloElRSwnc3yAVME5Zotryw+2fCeBq2rXsvguv1E49jr35xeGZVUQENMv9k6wA2LoNTQ6Ro6nk
    postgres-password: AgAh//by7CaWQlAPBM0bjfKnLhbj3pGb5Pb7o5+8AU9gXab4g4xwK7v+lfl0i2OZapfaC8M85hSU8sbfjk9RGziPPqDrESYViXponbpVnFn/oLZTBl7eUZVheS48WjGGdn26q2xruqssx50olTn5KbzRXUVnXu5N6yKO/O7dQuajtTBn7+EcTOhIxPNwwy34zXFa/IdwM3S7Gwi6KV5mck9iQ248BeIbP/HX+SJjJAvUrEfLC+GRkl611YwzZb45bpRdbGJz3Qq11xtl7jHfg0MQ1mT7vlY9dR0Ae9f0wg/TkQkOyGAIeUq7x7XJLviSnaEftIA3aQGAeMJlbWDxei4tQJt9VcrcnC/N2yUV2ZT99bbwBON5wBFt4f1M0zT89y/J18eUTdFod348IPSoFYxd6FvO0N4gV4beYZF7TrA0LpTbOmFVFmRDhX5SKpxGB7TP3+yMMTICF09sT1BzS89D8UQAOx4v7Xqohmb3ep1/VP74vyaDdrkVbrUPAOus6u55+0qmTf6beGDFXQRNPJxfuP9AZjGMG6jtxjuMgpyXkiTRB5wDt7iudgzSz16eymKmermm+wafMrJz4cGwB/RvRAm0SIeus/F1T8fPf9ESIzwmpJYETanBL/M0O7sL6aQg1gpSFJzjq0L3gD96gVLa/vj2+hrsFenVemJvU5VfOgzWO7UWwPrICVzlC/v7GI8FgMo5jC6kUdqK
  template:
    metadata:
      name: reactive-resume-postgresql
      namespace: reactive-resume
    type: Opaque
