apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nayris
spec:
  destination:
    namespace: nayris
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: manifests/apps/nayris/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  ignoreDifferences:
    - kind: "Namespace"
      jsonPointers:
      # - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      # selfHeal: false
    syncOptions:
      - RespectIgnoreDifferences=true
      # - CreateNamespace=true
