apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: '140'
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true
spec:
  servingCerts:
    namedCertificates:
      - names:
          - api.ocp.kounex.com
        servingCertificate:
          name: openshift-api-zz45z
