apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard
  namespace: cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: '140'
spec:
  duration: 1440h0m0s
  renewBefore: 360h0m0s
  commonName: '*.apps.ocp.kounex.com'
  dnsNames:
    - '*.apps.ocp.kounex.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: openshift-wildcard-certificate
