apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: '140'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  commonName: '*.apps.ocp.kounex.com'
  dnsNames:
    - '*.apps.ocp.kounex.com'
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: openshift-wildcard-certificate
