apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-api
  namespace: cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: '140'
spec:
  secretName: openshift-api-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  duration: 1440h0m0s
  renewBefore: 360h0m0s
  dnsNames:
    - 'api.ocp.kounex.com'
