apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-api
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: '140'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: openshift-api-zz45z
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'api.ocp.kounex.com'
