apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - lets-encrypt/sealed-secret-cloudflare-api-token.yml
  - lets-encrypt/cluster-issuer.yml

  - certificate-openshift-wildcard.yml
  - certificate-openshift-api.yml
  - ingress-controller.yml
  - api-server.yml
