apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: configs
  source:
    path: manifests/configs/sealed-secrets/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
