apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-app
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    path: manifests/configs/sealed-secrets/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secrets
  ignoreDifferences:
    - kind: Namespace
  syncPolicy:
    automated:
      prune: true
      
    syncOptions:
      - RespectIgnoreDifferences=true
