apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-web
  namespace: bluespice
spec:
  template:
    spec:
      containers:
        - name: wiki-web
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiki-task
  namespace: bluespice
spec:
  template:
    spec:
      containers:
        - name: wiki-task
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: database
  namespace: bluespice
spec:
  template:
    spec:
      containers:
        - name: database
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: database-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
    - metadata:
        name: database-logs
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: search
  namespace: bluespice
spec:
  template:
    spec:
      containers:
        - name: search
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
  volumeClaimTemplates:
    - metadata:
        name: search-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
