apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
