apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.5.2
    helm:
      releaseName: sealed-secrets
      values: |
        Args:
          - '--update-status'
        readinessProbe:
          initialDelaySeconds: 10
        podSecurityContext:
          fsGroup:
        containerSecurityContext:
          runAsUser:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: sealed-secrets
  ignoreDifferences:
    - kind: Namespace
  syncPolicy:
    automated:
      prune: true
      
    syncOptions:
      - RespectIgnoreDifferences=true
