apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-web
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: sealed-secrets
  source:
    chart: sealed-secrets-web
    repoURL: https://bakito.github.io/helm-charts
    targetRevision: 3.0.7
    helm:
      releaseName: sealed-secrets-web
      parameters:
        - name: 'image.args[0]'
          value: '--kubeseal-arguments=--controller-name=sealed-secrets --controller-namespace=sealed-secrets'
        # - name: 'image.args[1]'
        #   value: '--include-namespaces=sealed-secrets'
      values: |
        Args:
          - '--update-status'
        readinessProbe:
          initialDelaySeconds: 10
        podSecurityContext:
          fsGroup:
        containerSecurityContext:
          runAsUser:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
