apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: sealed-secrets
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.8.2
    helm:
      releaseName: sealed-secrets
      values: |
        Args:
          - '--update-status'
        readinessProbe:
          initialDelaySeconds: 10
        podSecurityContext:
          fsGroup:
        containerSecurityContext:
          runAsUser:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
