apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-web
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: configs
  source:
    chart: sealed-secrets-web
    repoURL: https://bakito.github.io/helm-charts
    targetRevision: 2.8.1
    helm:
      releaseName: sealed-secrets-web
      values: |
        Args:
          - '--update-status'
        readinessProbe:
          initialDelaySeconds: 10
        podSecurityContext:
          fsGroup:
        containerSecurityContext:
          runAsUser:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed-secrets
  ignoreDifferences:
    - kind: Namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - RespectIgnoreDifferences=true
