apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-project.yml

  - application-base.yml
  - application-web.yml

  # SCCs should not be patched like this
  # It's better to have RoleBindings making
  # use of a SCC to keep SCCs in base form
  # - patch-anyuid-scc.yml
  - role.yml
  - role-binding.yml

  - route-web.yml

commonLabels:
  app.kubernetes.io/part-of: sealed-secrets
