---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-web-services
  # namespace: kube-system
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - services
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sealed-secrets-web-services
  # namespace: sealed-secrets
subjects:
  - kind: ServiceAccount
    name: sealed-secrets-web
    namespace: sealed-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sealed-secrets-web-services
