apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brackets-db
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  project: brackets
  destination:
    namespace: brackets
    server: https://kubernetes.default.svc
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.2.8
    helm:
      values: |-


        global:
          storageClass: lvms-vg1
          postgresql:
            auth:
              username: bracket
              database: bracket_prod
              existingSecret: brackets-postgresql
        serviceAccount:
          create: true
          name: brackets-db

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
