apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: brackets-backend
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '220'
spec:
  destination:
    namespace: brackets
    server: https://kubernetes.default.svc
  project: brackets
  source:
    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 3.0.4
    helm:
      values: |-

        controllers:
          main:
            strategy: RollingUpdate

            annotations:
              openshift.io/required-scc: anyuid

            labels:
              app.openshift.io/runtime: nodejs

            containers:
              main:
                image:
                  repository: ghcr.io/evroon/bracket-backend
                  tag: v2.2.2
                  pullPolicy: IfNotPresent

                annotations:
                  openshift.io/required-scc: anyuid

                env:
                  - name: ENVIRONMENT
                    value: PRODUCTION
                  - name: PG_DSN
                    value: postgresql://brackets-db-postgresql:5432/bracket_prod
                  - name: CORS_ORIGIN_REGEX
                    value: https://*\.kounex\.com
                  - name: JWT_SECRET
                    value: 5cdd32f72a145ea257a569abf36b61050af70f541e92ddc8994b5577444775b97337c6c588f17d32e214536249d7c8f6312d014b03f474533557b86f159ea3995466f43ef5f6bd8992a09ef2ed4a553f6bf970674b62785955ccc5cb0bab7af43815556f2c800054862193fd0e4e3646fedf46fa5fa20396611137ed429ed267fe6994968df19f6cafbb09a3054d287525b4bd25cb74225c97bf953dabf2a9ce7906cebacdc576056b88b049098a901ba9261d96de3acacfc77a8eb643f26b0f4d92f9a225827ce9f284ba5092efc3c846b35a6492fc9206d1ffd89a533ba2e97b57c05fa74bb491dc2d8aca73b764d933d8517e4f63391a7911aa9b0d26a477
                  - name: ADMIN_EMAIL
                    valueFrom:
                      secretKeyRef:
                        name: brackets-admin
                        key: ADMIN_EMAIL
                  - name: ADMIN_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: brackets-admin
                        key: ADMIN_PASSWORD

        persistence:
          data:
            enabled: true
            storageClass: lvms-vg1
            accessMode: ReadWriteOnce
            size: 5Gi
            globalMounts:
              - path: /usr/app/backend/static

        service:
          main:
            enabled: true
            controller: main
            ports:
              http:
                port: 8400

        ingress:
          main:
            annotations:
              route.openshift.io/termination: "edge"
            hosts:
            - host: api.brackets.apps.ocp.kounex.com
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    identifier: main
                    port: http

        serviceAccount:
          create: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
