apiVersion: v1
kind: ConfigMap
metadata:
  name: bluespice-config
  namespace: bluespice
  labels:
    app.kubernetes.io/part-of: bluespice
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
data:
  VERSION: "5.2.4"
  EDITION: "free"
  TZ: "UTC"
  BACKUP_HOUR: "04"

  WIKI_NAME: "BlueSpice"
  WIKI_LANG: "en"
  WIKI_PASSWORDSENDER: "wiki@localhost"
  WIKI_EMERGENCYCONTACT: "wiki@localhost"
  WIKI_HOST: "REPLACE-IN-OVERLAY"
  WIKI_PORT: "443"
  WIKI_PROTOCOL: "https"
  WIKI_BASE_PATH: "/"

  DB_HOST: "database"
  DB_NAME: "bluespice"
  DB_PREFIX: ""
  DB_USER: "bluespice"
  DB_ROOT_USER: "root"

  SMTP_HOST: ""
  SMTP_PORT: ""
  SMTP_USER: ""
  SMTP_ID_HOST: ""

  CHAT_HOST: "-"

  WIKI_PRE_INIT_SETTINGS_FILE: "/data/wiki/pre-init-settings.php"

  WIRE_LOG_LEVEL: "debug"
  WIRE_WIKI_BASE_PATH: "http://wiki-web:9090"
