apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bluespice-secrets
  namespace: bluespice
  labels:
    app.kubernetes.io/part-of: bluespice
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: bluespice-secrets
  data:
    # Database credentials
    - secretKey: DB_PASS
      remoteRef:
        key: BLUESPICE_DB_PASS
    - secretKey: DB_ROOT_PASS
      remoteRef:
        key: BLUESPICE_DB_ROOT_PASS
    - secretKey: SMTP_PASS
      remoteRef:
        key: BLUESPICE_SMTP_PASS

    # Wiki internal secrets
    - secretKey: INTERNAL_WIKI_SECRETKEY
      remoteRef:
        key: BLUESPICE_WIKI_SECRETKEY
    - secretKey: INTERNAL_WIKI_UPGRADEKEY
      remoteRef:
        key: BLUESPICE_WIKI_UPGRADEKEY
    - secretKey: INTERNAL_WIKI_TOKEN_AUTH_SALT
      remoteRef:
        key: BLUESPICE_WIKI_TOKEN_AUTH_SALT

    # SimpleSAMLphp secrets
    - secretKey: INTERNAL_SIMPLESAMLPHP_ADMIN_PASS
      remoteRef:
        key: BLUESPICE_SIMPLESAMLPHP_ADMIN_PASS
    - secretKey: INTERNAL_SIMPLESAMLPHP_SECRET_SALT
      remoteRef:
        key: BLUESPICE_SIMPLESAMLPHP_SECRET_SALT

    # Wire API secrets
    - secretKey: INTERNAL_WIRE_API_KEY
      remoteRef:
        key: BLUESPICE_WIRE_API_KEY

    # Admin credentials
    - secretKey: WIKI_INITIAL_ADMIN_PASS
      remoteRef:
        key: BLUESPICE_ADMIN_PASS
