apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-operator-app
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '100'
spec:
  source:
    path: manifests/operators/cert-manager/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: main
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: operators
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
