apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: lvms-operator
  annotations:
    argocd.argoproj.io/sync-wave: '105'
spec:
  targetNamespaces:
    - openshift-storage
  upgradeStrategy: Default
