---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-application-controller-secrets
  namespace: openshift-config
rules:
  - verbs:
      - '*'
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-gitops-application-controller-secrets
  namespace: openshift-config
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-gitops-application-controller-secrets
