apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: chatbot-ui
  namespace: chatbot-ui
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
