apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-ui
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  destination:
    namespace: chatbot-ui
    server: https://kubernetes.default.svc
  project: chatbot-ui
  source:
    chart: app-template
    repoURL: https://bjw-s.github.io/helm-charts
    targetRevision: 1.3.2
    helm:
      values: |-
        image:
          repository: ghcr.io/kounex/chatbot-ui
          tag: 0.1.0-rc51
          pullPolicy: IfNotPresent

        controller:
          labels:
            app.openshift.io/runtime: nodejs

        serviceAccount:
          create: true

        service:
          main:
            ports:
              http:
                port: 3000

        ingress:
          main:
            enabled: true
            annotations:
              route.openshift.io/termination: "edge"
            hosts:
            - host: chatbot-ui.apps.ocp.kounex.com
              paths:
                - path: /
                  pathType: Prefix
                  service:
                    port: 3000

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: openshift-gitops
    syncOptions:
      - CreateNamespace=true
