kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: chatbot-ui
  namespace: chatbot-ui
  labels:
    app: chatbot-ui
    app.kubernetes.io/part-of: chatbot-ui
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  host: chatbot-ui.apps.ocp.kounex.com
  to:
    kind: Service
    name: chatbot-ui
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
