# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: patch-oauth-templates
#   namespace: openshift-config
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: patch-oauth-templates
# rules:
#   - apiGroups:
#       - config.openshift.io
#     resources:
#       - oauths
#     verbs:
#       - get
#       - list
#       - patch
#       - update
# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: patch-oauth-templates
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: patch-oauth-templates
# subjects:
#   - kind: ServiceAccount
#     name: patch-oauth-templates
#     namespace: openshift-config
# ---
# apiVersion: batch/v1
# kind: Job
# metadata:
#   name: patch-oauth-templates
#   namespace: openshift-config
#   annotations:
#     argocd.argoproj.io/hook: PostSync
#     argocd.argoproj.io/hook-delete-policy: HookSucceeded
# spec:
#   template:
#     spec:
#       containers:
#         - image: openshift/origin-cli
#           command:
#             - /bin/bash
#             - -c
#             - |
#               #!/usr/bin/env bash
#               if oc get oauth; then
#                 oc patch oauth cluster --type=merge --patch='{"spec": { "templates": { "login": { "name": "login-template" }, "providerSelection": { "name": "providers-template" }}}}'
#               else
#                 echo "Could not apply login-theme since the OAuth CR is missing - create one first!"
#                 exit 1
#               fi
#           name: patch-oauth-templates
#       dnsPolicy: ClusterFirst
#       restartPolicy: Never
#       terminationGracePeriodSeconds: 30
#       serviceAccount: patch-oauth-templates
#       serviceAccountName: patch-oauth-templates
kind: OAuth
apiVersion: config.openshift.io/v1
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
spec:
  templates:
    providerSelection:
      name: providers-template
    login:
      name: login-template
