
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  labels:
    app.kubernetes.io/instance: bootstrap
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  templates:
    login:
      name: login-template
    providerSelection:
      name: provider-template
