apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yt-cookies
  namespace: nayris
  annotations:
    argocd.argoproj.io/sync-wave: '230'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler
  target:
    name: yt-cookies
    creationPolicy: Owner
  data:
    - secretKey: cookies.txt
      remoteRef:
        key: NAYRIS_YT_COOKIES