apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sharry-app
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: apps
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    path: manifests/apps/sharry/apps
    repoURL: https://github.com/Kounex/ocp-gitops.git
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
